# Site settings
title: JamesOrrIV
email: me@jamesorriv.com
description: "Just my little corner of the internet where I can mess around with web tech and post my thoughts."
baseurl: ""
url: "http://jamesorriv.com"
github_username:  jamesorriv
goodreads_username: jamesorriv
linkedin_username: jamesorriv
steam_username: orr

TZ: America/Los_Angeles

# Build settings
markdown: kramdown
permalink: pretty
